# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

env:
  - TOX_ENV=py27
  - TOX_ENV=flake8

addons:
  apt:
    sources:
      - boost-latest

addons:
  apt:
    packages:
      - libjudy-dev
      - libboost1.55-dev
      - libboost-test1.55-dev
      - libboost-program-options1.55-dev
      - libboost-system1.55-dev
      - libboost-filesystem1.55-dev
      - libevent-dev
      - automake
      - libtool
      - flex 
      - bison
      - pkg-config
      - g++
      - libssl-dev

before_install:
  - bash build/travis/install-thrift.sh
  - bash build/travis/install-nanomsg.sh

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements.txt
  - pip install tox
  - cd pd_mk/ && ./autogen.sh && ./configure 'P4_PATH=tests/test.p4' 'P4_PREFIX=test' && make all && cd ..

# command to run tests, e.g. python setup.py test
script:
  - tox -e $TOX_ENV
  - cd pd_mk/; make check; cd ..

after_success:
  # Report coverage results to codecov.io
  - pip install codecov
  - codecov
